TYPE=VIEW
query=select `acuaticovf`.`empleado`.`ID_Empleado` AS `ID_Empleado`,concat(`acuaticovf`.`empleado`.`Nombre_Empleado`,\' \',`acuaticovf`.`empleado`.`AP_Paterno`,\' \',`acuaticovf`.`empleado`.`Ap_Materno`) AS `Nombre Completo`,`acuaticovf`.`empleado`.`Fecha_Nac` AS `Fecha_Nac`,`acuaticovf`.`empleado`.`Fecha_Ingr` AS `Fecha_Ingr`,`acuaticovf`.`empleado`.`Puesto` AS `Puesto` from `acuaticovf`.`empleado`
md5=58109eb3a840cd24deef69308cb7da48
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2017-05-29 00:57:05
create-version=2
source=select `empleado`.`ID_Empleado` AS `ID_Empleado`,concat(`empleado`.`Nombre_Empleado`,\' \',`empleado`.`AP_Paterno`,\' \',`empleado`.`Ap_Materno`) AS `Nombre Completo`,`empleado`.`Fecha_Nac` AS `Fecha_Nac`,`empleado`.`Fecha_Ingr` AS `Fecha_Ingr`,`empleado`.`Puesto` AS `Puesto` from `empleado`
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_general_ci
view_body_utf8=select `acuaticovf`.`empleado`.`ID_Empleado` AS `ID_Empleado`,concat(`acuaticovf`.`empleado`.`Nombre_Empleado`,\' \',`acuaticovf`.`empleado`.`AP_Paterno`,\' \',`acuaticovf`.`empleado`.`Ap_Materno`) AS `Nombre Completo`,`acuaticovf`.`empleado`.`Fecha_Nac` AS `Fecha_Nac`,`acuaticovf`.`empleado`.`Fecha_Ingr` AS `Fecha_Ingr`,`acuaticovf`.`empleado`.`Puesto` AS `Puesto` from `acuaticovf`.`empleado`
mariadb-version=100121
